apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-obxn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-obxn@sha256:8eff9c4fc583c4b1b0cacf8ad210fe57289bcbb86ddc09c833002728e4253d8d
        name: my-nodejs
        resources: {}
status: {}
